# This Travis-CI file for testing the build, and eventually the
# functionality of the libfms library.
#
# This Travis-CI file was created based off the NOAA-GFDL/MOM6
# Travis-CI file.

# FMS is not a c-language project, although there are a few c-language
# sources.  However, this is the best choice.
language: c
os: linux
dist: bionic

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - pkg-config 
    - netcdf-bin 
    - libnetcdf-dev 
    - libnetcdff-dev 
    - openmpi-bin 
    - libopenmpi-dev 
    - gfortran

# Travis sets CC to gcc, but we need to ensure it is not set, so we can use mpicc
before_install:
  - test -n "$CC" && unset CC

before_script:
  - export CC=mpicc
  - export FC=mpif90
  - export CPPFLAGS='-I/usr/include -Duse_LARGEFILE -DMAXFIELDMETHODS_=500'
  - export FCFLAGS='-fcray-pointer -fdefault-double-8 -fdefault-real-8 -Waliasing -ffree-line-length-none -fno-range-check'
  - export LDFLAGS='-L/usr/lib'

script:
  - autoreconf -i
  - ./configure
  - make -j distcheck
 
