name: do-the-job
on: pull_request
jobs:
  start-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          #ec2-image-id: ami-092a9e946def5be32
          ec2-image-id: ami-02e136e904f3da870
          ec2-instance-type: m5.4xlarge
          subnet-id: subnet-02829d7b8c3522644
          security-group-id: sg-09f60dd1eeea6d55f
          #subnet-id: subnet-003faaf9f1e386979
          #security-group-id: sg-05735797b251348e2
       ##   iam-role-name: arn:aws:iam::430073024411:user/fms_test
  do-the-job:
    name: Do the job on the runner
    needs: start-runner # required to start the main job when the runner is ready
    runs-on: ${{ needs.start-runner.outputs.label }} # run the job on the newly created runner
    steps:
      - name: Install epel 
        run:  sudo amazon-linux-extras install epel -y
      - name: config epel 
        run:  sudo yum-config-manager --enable epel
      - name: Install singularity
        run:  sudo yum install -y singularity git
      - name: Clone from git
        run: git clone https://github.com/thomas-robinson/build_fms_script.git
      - name: Pull the container
        run:  singularity pull docker://thomasrobinson/model_environment:i2021.2
      - name: Build FMS in the container
        run:  singularity exec model_environment_i2021.2.sif ./build_fms.sh
  stop-runner:
    name: Stop self-hosted EC2 runner
    needs:
      - start-runner # required to get output from the start-runner job
      - do-the-job # required to wait when the main job is done
    runs-on: ubuntu-latest
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.start-runner.outputs.label }}
          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
 ## optional, requires additional permissions
  #        aws-resource-tags: > # optional, requires additional permissions
   #         [
    #          {"Key": "Name", "Value": "ec2-github-runner"},
     #         {"Key": "GitHubRepository", "Value": "${{ github.repository }}"}
      #      ]
